### ISSUE TITLE
Some edge cases

### ISSUE THREAD

**Issue by saltanovas** [getkevin/kevin-jvm#14]
After some time of library usage, I noticed some issues:

1. 401 error code is not handled properly. Response body in such situation is always `Unautohorized`. So `KevinApiErrorException.responseBody` will always be null since response body is not valid json:
<img width="494" alt="Screenshot 2022-03-01 at 16 45 45" src="https://user-images.githubusercontent.com/65735690/156192611-ee5cb1d5-5c05-4541-a60b-d860978184cb.png">

2. `InitiatePaymentResponse.confirmLink` is nullable. I don't think that it is possible. Or is it?

**Comment by grantas33** [comment]
1. I think it's fine since such a response body is redundant when HTTP status code 401 (which means Unauthorized) is returned.
2. It is possible that confirm link is null if making no-SCA payments.

**Comment by saltanovas** [comment]
@grantas33 do you meant that if I create a payment with token and choose Swedbank, for instance, which allows to confirm payment without second SCA if amount is less than X, then payment link wouldn't be returned? :OO

**Comment by grantas33** [comment]
@saltanovas Yes it should not return it
